-- Part – A

-- 1. Create INSTEAD OF DELETE trigger to prevent deletion
--    of employee records and store deleted data into EMPLOYEE_LOG table.

CREATE TRIGGER TRG_DELETE
ON EMPLOYEE
INSTEAD OF DELETE
AS
BEGIN
    DECLARE @EID INT, @NAME VARCHAR(100);

    SELECT @EID = EID FROM DELETED;
    SELECT @NAME = FIRSTNAME FROM DELETED;

    INSERT INTO EMPLOYEE_LOG
    (EID, OLDVALUE, NEWVALUE, FIELDNAME, OPERATIONTYPE, LOGDATE)
    VALUES
    (@EID, @NAME, NULL, 'FIRSTNAME', 'DELETE', GETDATE());

    PRINT 'DELETE NOT ALLOWED';
END;

DROP TRIGGER TRG_DELETE;


-- 2. Create trigger for preventing removal of employees from the table.

CREATE TRIGGER TRG_BLOCK_DELETE
ON EMPLOYEE
INSTEAD OF DELETE
AS
BEGIN
    PRINT 'EMPLOYEE CANNOT BE DELETED';
END;

DROP TRIGGER TRG_BLOCK_DELETE;


-- 3. Create INSTEAD OF trigger to log all operations
--    on EMPLOYEE table.

-- INSERT

CREATE TRIGGER TRG_INSERT_LOG
ON EMPLOYEE
INSTEAD OF INSERT
AS
BEGIN
    DECLARE @EID INT;

    SELECT @EID = EID FROM INSERTED;

    INSERT INTO EMPLOYEE_LOG
    (EID, OLDVALUE, NEWVALUE, FIELDNAME, OPERATIONTYPE, LOGDATE)
    VALUES
    (@EID, NULL, 'NEW RECORD', 'EMPLOYEE', 'INSERT', GETDATE());

    INSERT INTO EMPLOYEE
    SELECT * FROM INSERTED;
END;

DROP TRIGGER TRG_INSERT_LOG;


-- UPDATE

CREATE TRIGGER TRG_UPDATE_LOG
ON EMPLOYEE
INSTEAD OF UPDATE
AS
BEGIN
    DECLARE @EID INT,
            @OLDNAME VARCHAR(100),
            @NEWNAME VARCHAR(100);

    SELECT @EID = EID FROM INSERTED;
    SELECT @OLDNAME = FIRSTNAME FROM DELETED;
    SELECT @NEWNAME = FIRSTNAME FROM INSERTED;

    INSERT INTO EMPLOYEE_LOG
    (EID, OLDVALUE, NEWVALUE, FIELDNAME, OPERATIONTYPE, LOGDATE)
    VALUES
    (@EID, @OLDNAME, @NEWNAME, 'FIRSTNAME', 'UPDATE', GETDATE());

    UPDATE E
    SET FIRSTNAME = I.FIRSTNAME
    FROM EMPLOYEE E
    JOIN INSERTED I
    ON E.EID = I.EID;
END;

DROP TRIGGER TRG_UPDATE_LOG;


-- DELETE

CREATE TRIGGER TRG_DELETE_LOG
ON EMPLOYEE
INSTEAD OF DELETE
AS
BEGIN
    DECLARE @EID INT,
            @NAME VARCHAR(100);

    SELECT @EID = EID FROM DELETED;
    SELECT @NAME = FIRSTNAME FROM DELETED;

    INSERT INTO EMPLOYEE_LOG
    (EID, OLDVALUE, NEWVALUE, FIELDNAME, OPERATIONTYPE, LOGDATE)
    VALUES
    (@EID, @NAME, NULL, 'FIRSTNAME', 'DELETE', GETDATE());
END;

DROP TRIGGER TRG_DELETE_LOG;


-- 4. Create trigger to block employees from updating
--    their JOININGYEAR.

CREATE TRIGGER TRG_JOINYEAR
ON EMPLOYEE
INSTEAD OF UPDATE
AS
BEGIN
    IF UPDATE(JOININGYEAR)
    BEGIN
        PRINT 'EMPLOYEES ARE NOT ALLOWED TO UPDATE JOINING YEAR';
    END
    ELSE
    BEGIN
        UPDATE E
        SET FIRSTNAME = I.FIRSTNAME,
            LASTNAME = I.LASTNAME,
            CITY = I.CITY,
            GENDER = I.GENDER,
            DEPARTMENT = I.DEPARTMENT
        FROM EMPLOYEE E
        JOIN INSERTED I
        ON E.EID = I.EID;
    END
END;

DROP TRIGGER TRG_JOINYEAR;


-- 5. Create trigger for preventing duplicate employee
--    records having same FIRSTNAME, LASTNAME and CITY.

CREATE TRIGGER TRG_DUPLICATE
ON EMPLOYEE
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS
    (
        SELECT *
        FROM EMPLOYEE E
        JOIN INSERTED I
        ON E.FIRSTNAME = I.FIRSTNAME
        AND E.LASTNAME = I.LASTNAME
        AND E.CITY = I.CITY
    )
    BEGIN
        PRINT 'DUPLICATE RECORD NOT ALLOWED';
    END
    ELSE
    BEGIN
        INSERT INTO EMPLOYEE
        SELECT * FROM INSERTED;
    END
END;

DROP TRIGGER TRG_DUPLICATE;


-- Part – B

-- 6. Create INSTEAD OF INSERT trigger to prevent
--    insertion of duplicate EID.

CREATE TRIGGER TRG_EID
ON EMPLOYEE
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS
    (
        SELECT *
        FROM EMPLOYEE E
        JOIN INSERTED I
        ON E.EID = I.EID
    )
    BEGIN
        PRINT 'DUPLICATE EID NOT ALLOWED';
    END
    ELSE
    BEGIN
        INSERT INTO EMPLOYEE
        SELECT * FROM INSERTED;
    END
END;

DROP TRIGGER TRG_EID;


-- 7. Create INSTEAD OF UPDATE trigger to maintain
--    employee update history.

CREATE TRIGGER TRG_UPDATE
ON EMPLOYEE
INSTEAD OF UPDATE
AS
BEGIN
    DECLARE @EID INT,
            @OLDNAME VARCHAR(100),
            @NEWNAME VARCHAR(100);

    SELECT @EID = EID FROM INSERTED;
    SELECT @OLDNAME = FIRSTNAME FROM DELETED;
    SELECT @NEWNAME = FIRSTNAME FROM INSERTED;

    INSERT INTO EMPLOYEE_LOG
    (EID, OLDVALUE, NEWVALUE, FIELDNAME, OPERATIONTYPE, LOGDATE)
    VALUES
    (@EID, @OLDNAME, @NEWNAME, 'FIRSTNAME', 'UPDATE', GETDATE());

    UPDATE E
    SET FIRSTNAME = I.FIRSTNAME
    FROM EMPLOYEE E
    JOIN INSERTED I
    ON E.EID = I.EID;
END;

DROP TRIGGER TRG_UPDATE;


-- 8. Create INSTEAD OF UPDATE trigger to prevent
--    changing employee EID.

CREATE TRIGGER TRG_BLOCK_EID
ON EMPLOYEE
INSTEAD OF UPDATE
AS
BEGIN
    IF UPDATE(EID)
    BEGIN
        PRINT 'EID CANNOT BE CHANGED';
    END
    ELSE
    BEGIN
        UPDATE E
        SET FIRSTNAME = I.FIRSTNAME,
            LASTNAME = I.LASTNAME,
            CITY = I.CITY,
            GENDER = I.GENDER,
            DEPARTMENT = I.DEPARTMENT,
            JOININGYEAR = I.JOININGYEAR
        FROM EMPLOYEE E
        JOIN INSERTED I
        ON E.EID = I.EID;
    END
END;

DROP TRIGGER TRG_BLOCK_EID;


-- 9. Create INSTEAD OF INSERT trigger to block
--    insertion of employees with NULL department.

CREATE TRIGGER TRG_DEPARTMENT
ON EMPLOYEE
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS
    (
        SELECT *
        FROM INSERTED
        WHERE DEPARTMENT IS NULL
    )
    BEGIN
        PRINT 'DEPARTMENT CANNOT BE NULL';
    END
    ELSE
    BEGIN
        INSERT INTO EMPLOYEE
        SELECT * FROM INSERTED;
    END
END;

DROP TRIGGER TRG_DEPARTMENT;


-- 10. Create INSTEAD OF UPDATE trigger to prevent
--     updating GENDER column.

CREATE TRIGGER TRG_GENDER
ON EMPLOYEE
INSTEAD OF UPDATE
AS
BEGIN
    IF UPDATE(GENDER)
    BEGIN
        PRINT 'GENDER CANNOT BE UPDATED';
    END
    ELSE
    BEGIN
        UPDATE E
        SET FIRSTNAME = I.FIRSTNAME,
            LASTNAME = I.LASTNAME,
            CITY = I.CITY,
            DEPARTMENT = I.DEPARTMENT,
            JOININGYEAR = I.JOININGYEAR
        FROM EMPLOYEE E
        JOIN INSERTED I
        ON E.EID = I.EID;
    END
END;

DROP TRIGGER TRG_GENDER;


-- =========================================================
-- Part – C
-- =========================================================

CREATE TABLE STUDENT_LOG
(
    LOGID INT IDENTITY(1,1),
    STDID INT,
    SNAME VARCHAR(50),
    OLDVALUE VARCHAR(100),
    NEWVALUE VARCHAR(100),
    FIELDNAME VARCHAR(50),
    OPERATIONTYPE VARCHAR(20),
    LOGDATE DATETIME
);


-- 11. Create INSTEAD OF INSERT trigger to prevent
--     insertion of students whose SPI is greater than 10
--     or less than 0.

CREATE TRIGGER TRG_SPI
ON STUDENT
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS
    (
        SELECT *
        FROM INSERTED
        WHERE SPI > 10 OR SPI < 0
    )
    BEGIN
        PRINT 'INVALID SPI';
    END
    ELSE
    BEGIN
        INSERT INTO STUDENT
        SELECT * FROM INSERTED;
    END
END;

DROP TRIGGER TRG_SPI;


-- 12. Create INSTEAD OF UPDATE trigger to block
--     students from changing their BRANCH.

CREATE TRIGGER TRG_BRANCH
ON STUDENT
INSTEAD OF UPDATE
AS
BEGIN
    IF UPDATE(BRANCH)
    BEGIN
        PRINT 'BRANCH CANNOT BE CHANGED';
    END
    ELSE
    BEGIN
        UPDATE S
        SET SNAME = I.SNAME,
            CITY = I.CITY,
            SPI = I.SPI
        FROM STUDENT S
        JOIN INSERTED I
        ON S.STDID = I.STDID;
    END
END;

DROP TRIGGER TRG_BRANCH;


-- 13. Create INSTEAD OF DELETE trigger to move deleted
--     student records into STUDENT_LOG.

CREATE TRIGGER TRG_STUDENT_DELETE
ON STUDENT
INSTEAD OF DELETE
AS
BEGIN
    DECLARE @ID INT,
            @NAME VARCHAR(50);

    SELECT @ID = STDID FROM DELETED;
    SELECT @NAME = SNAME FROM DELETED;

    INSERT INTO STUDENT_LOG
    (STDID, SNAME, OLDVALUE, NEWVALUE,
     FIELDNAME, OPERATIONTYPE, LOGDATE)
    VALUES
    (@ID, @NAME, @NAME, NULL,
     'STUDENT', 'DELETE', GETDATE());

    PRINT 'STUDENT DELETED DATA STORED IN LOG';
END;

DROP TRIGGER TRG_STUDENT_DELETE;


-- 14. Create INSTEAD OF UPDATE trigger to prevent
--     updating student SPI.

CREATE TRIGGER TRG_BLOCK_SPI
ON STUDENT
INSTEAD OF UPDATE
AS
BEGIN
    IF UPDATE(SPI)
    BEGIN
        PRINT 'SPI CANNOT BE UPDATED';
    END
    ELSE
    BEGIN
        UPDATE S
        SET SNAME = I.SNAME,
            CITY = I.CITY,
            BRANCH = I.BRANCH
        FROM STUDENT S
        JOIN INSERTED I
        ON S.STDID = I.STDID;
    END
END;

DROP TRIGGER TRG_BLOCK_SPI;


-- 15. Create INSTEAD OF UPDATE trigger to store
--     student branch transfer history.

CREATE TRIGGER TRG_BRANCH_LOG
ON STUDENT
INSTEAD OF UPDATE
AS
BEGIN
    DECLARE @ID INT,
            @OLD VARCHAR(50),
            @NEW VARCHAR(50);

    SELECT @ID = STDID FROM INSERTED;
    SELECT @OLD = BRANCH FROM DELETED;
    SELECT @NEW = BRANCH FROM INSERTED;

    INSERT INTO STUDENT_LOG
    (STDID, SNAME, OLDVALUE, NEWVALUE,
     FIELDNAME, OPERATIONTYPE, LOGDATE)
    VALUES
    (@ID, NULL, @OLD, @NEW,
     'BRANCH', 'UPDATE', GETDATE());

    UPDATE S
    SET SNAME = I.SNAME,
        CITY = I.CITY,
        SPI = I.SPI,
        BRANCH = I.BRANCH
    FROM STUDENT S
    JOIN INSERTED I
    ON S.STDID = I.STDID;
END;

DROP TRIGGER TRG_BRANCH_LOG;